-- Update RM passwords
-- Note: This requires bcrypt hashes generated by Node.js
-- Run the TypeScript script first, or use the auth service to generate hashes

-- This SQL file shows what needs to be updated
-- The actual password hashes must be generated using bcrypt.hash() in Node.js

-- Example: For rm1 with password "rm1123456"
-- The hash would be generated by: bcrypt.hash('rm1123456', 10)
-- Then update: UPDATE users SET password_hash = '<generated_hash>' WHERE username = 'rm1';


